name: Tests secrets and variables
on : push
jobs:
  return-values:
    runs-on: ubuntu-latest
    outputs:
      MON_RETOUR: ${{ steps.return-step.outputs.result }}
    steps:
      - name: GitHub Script
        id: return-step
        uses: actions/github-script@v7.0.1
        with:
          script: return "Job ok";
  display-return:
    runs-on: ubuntu-latest
    needs: return-values
    steps:
      - name: Display return
        run: echo "${{ needs.return-values.outputs.MON_RETOUR }}"
              
          
          
