name: Tests artifacts
on : [merge_group]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mon application" > my_app.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with: 
          name: app-to-deploy
          path: my_app.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: app-to-deploy         
      - run: |
          ls
          cat my_app.txt
              
          
          
